Add Geckodriver support
inviqa/hem-tasks-selenium pull request #2
Opened 2016-11-14 15:47 UTC by elvetemedve

Download the paltform specific Geckodriver when needed and start
selenium server with using it.
This decouples Selenium from the Firefox version installed on the host
machine.

2016-11-14 16:03 UTC, kierenevans requested changes
Good additions, just need a bit of cleanup.

2016-11-14 16:03 UTC, kierenevans commented on lib/hem/tasks/selenium/gecko.rb
> +        '&& sudo yum install unzip tar -y',
No point switching based on FFI Platform for the download URL if we are going to assume `yum`

2016-11-14 16:03 UTC, kierenevans commented on lib/hem/tasks/selenium/gecko.rb
> +        '&& if [[ $(file --mime-type ./bin/chromedriver.zip) == *'application/zip' ]]; then unzip ./bin/chromedriver.zip -d ./bin/; else tar -xvf ./bin/chromedriver.zip -C ./bin/; fi',
Unquoted string at the end?

2016-11-14 16:03 UTC, kierenevans commented on lib/hem/tasks/selenium/gecko.rb
> +namespace :chromedriver do
Namespace needs updating

2016-11-15 17:30 UTC, elvetemedve commented on lib/hem/tasks/selenium/gecko.rb
> +        '&& sudo yum install unzip tar -y',
`FFI::Platform` tells the platform of the host machine, while `yum` is executed in the VM.
So downloading and extracting the driver will happen in the VM.

2016-11-15 17:32 UTC, elvetemedve commented
@kierenevans I've updated the PR.

2016-11-16 09:04 UTC, kierenevans commented on lib/hem/tasks/selenium/gecko.rb
> +        '&& sudo yum install unzip tar -y',
Got you!

2016-11-16 09:05 UTC, kierenevans approved these changes

2016-11-16 09:05 UTC, merged